# WorldEditCUI Plugin by KennyTV

# If enabled, the positions for particles will only be calculated once per selection and then cached.
# This essentially entirely removes the higher CPU usage of the calculations, but results in some caching if many/big selections are being made.
#
# Disable this if you run into concurreny errors.
cache-calculated-positions: true

# A list of all particles can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Particle.html
# Just note that newly introduced particles obviously won't work in older versions.
# Shown for the selection you currently have.
particle: FLAME
# Shown for the copied selection after using the WorldEdit //copy command.
# Can be enabled with the '/wecui toggleclipboard' command.
copy-region-particle: VILLAGER_HAPPY

# How many particles should be displayed for every block of length.
# The recommended amount is between 2 and 4. Can be set from 1 to 5.
particles-per-block: 3

# This number determines how many ticks should be between every sending of particles.
# Can be set from 5 to 200.
# For reference: 20 Minecraft ticks are equivalent to 1 second -> 10 ticks are 0.5 seconds -> 1 tick is 0.05 seconds.
particle-send-interval: 12

advanced-grid:
  # If enabled, the selection will not only be displayed by the outline,
  # but also with a grid between the outlines (the bigger the selection, the bigger the grid).
  # Requires more or less 2 to 3 times the amount of calculations, but looks amazing!
  enabled: false
  # How many particles should be displayed for every block of length.
  # The recommended amount is between 2 and 3. Can be set from 2 to 5.
  particles-per-block: 2

particle-expiry:
  # If enabled and a selection isn't changed for the given amount of seconds, particles will stop being sent for it
  enabled: false
  expires-after-seconds: 180
  # If enabled, players are notified if their particles disappear after the expiry.
  expire-message: true

# If enabled, the particles will be sent to all players, rather than just to the player having the WorldEdit selection.
# Might be useful when building as a group.
send-particles-to-all: false

# If set to 'none', every player will have their selection displayed.
# Else, only players with the set permission will have particles for their selection.
permission: "none"

# If set to false, players will have to use '/wecui toggle' first to be able to see the particles.
show-selection-by-default: true
# If set to false, players will have to use '/wecui toggleclipboard' first to be able to see the particles.
show-clipboard-by-default: false

# Saves toggles to a file, so that they stay changed after player quits and server restarts.
# This also includes the clipboard toggle.
persistent-toggles: false

# Changes the distance from which particles can be seen, can be set from 1 to 500 (if you for some reason want to see them 500 blocks away).
# This does NOT affect server performance in any way.
particle-viewdistance: 99

# Recommended to have this enabled, as you'd else miss out on new features and overall improvements.
update-checks: true