name: ${project.name}
version: ${project.version}
main: eu.kennytv.worldeditcui.WorldEditCUIPlugin
authors: [KennyTV]
depend: [WorldEdit]
website: https://www.spigotmc.org/resources/worldeditcui.60726/
api-version: 1.13

commands:
  worldeditcui:
    description: WorldEditCUI main command.
    aliases: [wecui]